# fly.toml app configuration file generated for vademecumapp on 2026-07-19T00:48:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vademecumapp" primary_region = "ams"

[build] dockerfile = "Dockerfile"

[[services]] internal_port = 3838 protocol = "tcp"

[services.concurrency] type = "connections" soft_limit = 20 hard_limit = 25

[[services.ports]] handlers = ["http"] port = 80

[[services.ports]] handlers = ["tls", "http"] port = 443

[env] PORT = "3838"
